{% set version = '2.3.0' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-r6
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/R6_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/R6/R6_{{ version }}.tar.gz
  sha256: 05b5e117659796c67a16de0854661b25d0739da53a8cb93dcfc528d4c185fac9

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: knitr, microbenchmark, pryr, testthat, ggplot2, scales
requirements:
  build:
    - {{posix}}zip               # [win]

  host:
    - r-base

  run:
    - r-base

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('R6')"           # [not win]
    - "\"%R%\" -e \"library('R6')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/r-lib/R6/
  license: MIT + file LICENSE
  summary: Creates classes with reference semantics, similar to R's built-in reference classes.
    Compared to reference classes, R6 classes are simpler and lighter-weight, and they
    are not built on S4 classes so they do not require the methods package. These classes
    allow public and private members, and they support inheritance, even when the classes
    are defined in different packages.
  license_family: MIT

# The original CRAN metadata for this package was:

# Package: R6
# Title: Classes with Reference Semantics
# Version: 2.3.0
# Authors@R: person("Winston", "Chang", role = c("aut", "cre"), email = "winston@stdout.org")
# Description: Creates classes with reference semantics, similar to R's built-in reference classes. Compared to reference classes, R6 classes are simpler and lighter-weight, and they are not built on S4 classes so they do not require the methods package. These classes allow public and private members, and they support inheritance, even when the classes are defined in different packages.
# Depends: R (>= 3.0)
# Suggests: knitr, microbenchmark, pryr, testthat, ggplot2, scales
# License: MIT + file LICENSE
# URL: https://github.com/r-lib/R6/
# LazyData: true
# BugReports: https://github.com/r-lib/R6/issues
# RoxygenNote: 6.1.0.9000
# NeedsCompilation: no
# Packaged: 2018-10-04 14:48:18 UTC; winston
# Author: Winston Chang [aut, cre]
# Maintainer: Winston Chang <winston@stdout.org>
# Repository: CRAN
# Date/Publication: 2018-10-04 15:30:03 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
