{% set version = '1.8.10' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-psych
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/psych_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/psych/psych_{{ version }}.tar.gz
  sha256: e8901ddab14729bfccbd82a8824fbb6523c10c2cd8fb7199b1ca56a7ffcb6e58

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: GPArotation, lavaan, sem, lme4,Rcsdp, graph, Rgraphviz
requirements:
  build:
    - {{posix}}zip               # [win]

  host:
    - r-base
    - r-foreign
    - r-lattice
    - r-mnormt
    - r-nlme

  run:
    - r-base
    - r-foreign
    - r-lattice
    - r-mnormt
    - r-nlme

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('psych')"           # [not win]
    - "\"%R%\" -e \"library('psych')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://personality-project.org/r/psych https://personality-project.org/r/psych-manual.pdf
  license: GPL (>= 2)
  summary: A general purpose toolbox for personality, psychometric theory and experimental psychology.   Functions
    are primarily for multivariate analysis and scale construction using factor analysis,
    principal component analysis, cluster analysis and reliability analysis, although
    others provide basic descriptive statistics. Item Response Theory is done using  factor
    analysis of tetrachoric and polychoric correlations. Functions for analyzing data
    at multiple levels include within and between group statistics, including correlations
    and factor analysis.   Functions for simulating and testing particular item and
    test structures are included. Several functions  serve as a useful front end for
    structural equation modeling.  Graphical displays of path diagrams, factor analysis
    and structural equation models are created using basic graphics. Some of the functions
    are written to support a book on psychometric theory as well as publications in
    personality research. For more information, see the <https://personality-project.org/r>
    web page.
  license_family: GPL3

# The original CRAN metadata for this package was:

# Package: psych
# Version: 1.8.10
# Date: 2018-10-24
# Title: Procedures for Psychological, Psychometric, and Personality Research
# Authors@R: person("William", "Revelle", role =c("aut","cre"), email="revelle@northwestern.edu", comment=c(ORCID  = "0000-0003-4880-9610") )
# Description: A general purpose toolbox for personality, psychometric theory and experimental psychology.   Functions are primarily for multivariate analysis and scale construction using factor analysis, principal component analysis, cluster analysis and reliability analysis, although others provide basic descriptive statistics. Item Response Theory is done using  factor analysis of tetrachoric and polychoric correlations. Functions for analyzing data at multiple levels include within and between group statistics, including correlations and factor analysis.   Functions for simulating and testing particular item and test structures are included. Several functions  serve as a useful front end for structural equation modeling.  Graphical displays of path diagrams, factor analysis and structural equation models are created using basic graphics. Some of the functions are written to support a book on psychometric theory as well as publications in personality research. For more information, see the <https://personality-project.org/r> web page.
# License: GPL (>= 2)
# Imports: mnormt,parallel,stats,graphics,grDevices,methods,foreign,lattice,nlme
# Suggests: GPArotation, lavaan, sem, lme4,Rcsdp, graph, Rgraphviz
# LazyData: true
# ByteCompile: TRUE
# URL: https://personality-project.org/r/psych https://personality-project.org/r/psych-manual.pdf
# NeedsCompilation: no
# Packaged: 2018-10-30 20:28:29 UTC; wr
# Author: William Revelle [aut, cre] (<https://orcid.org/0000-0003-4880-9610>)
# Maintainer: William Revelle <revelle@northwestern.edu>
# Depends: R (>= 2.10)
# Repository: CRAN
# Date/Publication: 2018-10-31 11:10:03 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
