{% set version = '0.6.3' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-googleauthr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/googleAuthR_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/googleAuthR/googleAuthR_{{ version }}.tar.gz
  sha256: 1d2d3bbf29c6abb0963c2ad23bc30503fd6e696894433e309d8c0637276ebd0c

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: bigQueryR, covr, devtools (>= 1.12.0), formatR (>= 1.4), googleAnalyticsR, httptest, knitr, miniUI (>= 0.1.1), rmarkdown, roxygen2 (>= 5.0.0), shiny (>= 0.13.2), testthat
requirements:
  build:
    - {{posix}}zip               # [win]

  host:
    - r-base
    - r-r6 >=2.1.0
    - r-assertthat >=0.2.0
    - r-digest
    - r-httr >=1.3.1
    - r-jsonlite >=0.9.16
    - r-memoise >=1.1.0

  run:
    - r-base
    - r-r6 >=2.1.0
    - r-assertthat >=0.2.0
    - r-digest
    - r-httr >=1.3.1
    - r-jsonlite >=0.9.16
    - r-memoise >=1.1.0

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('googleAuthR')"           # [not win]
    - "\"%R%\" -e \"library('googleAuthR')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: http://code.markedmondson.me/googleAuthR/
  license: MIT + file LICENSE
  summary: Create R functions that interact with OAuth2 Google APIs  <https://developers.google.com/apis-explorer/>
    easily, with auto-refresh and Shiny compatibility.
  license_family: MIT

# The original CRAN metadata for this package was:

# Package: googleAuthR
# Type: Package
# Version: 0.6.3
# Title: Authenticate and Create Google APIs
# Description: Create R functions that interact with OAuth2 Google APIs  <https://developers.google.com/apis-explorer/> easily, with auto-refresh and Shiny compatibility.
# Authors@R: c(person("Mark", "Edmondson",email = "m@sunholo.com", role = c("aut", "cre"), comment = c(ORCID = "0000-0002-8434-3881")), person("Jennifer", "Bryan",email="jenny@stat.ubc.ca", role = "ctb"), person("Johann", "deBoer", email="johanndeboer@gmail.com", role = "ctb"), person("Neal", "Richardson", email="neal.p.richardson@gmail.com", role = "ctb"))
# URL: http://code.markedmondson.me/googleAuthR/
# BugReports: https://github.com/MarkEdmondson1234/googleAuthR/issues
# Depends: R (>= 3.3.0)
# Imports: assertthat (>= 0.2.0), digest, httr (>= 1.3.1), jsonlite (>= 0.9.16), R6 (>= 2.1.0), memoise (>= 1.1.0), utils
# Suggests: bigQueryR, covr, devtools (>= 1.12.0), formatR (>= 1.4), googleAnalyticsR, httptest, knitr, miniUI (>= 0.1.1), rmarkdown, roxygen2 (>= 5.0.0), shiny (>= 0.13.2), testthat
# License: MIT + file LICENSE
# LazyData: true
# VignetteBuilder: knitr
# RoxygenNote: 6.0.1
# NeedsCompilation: no
# Packaged: 2018-06-21 12:29:56 UTC; mark
# Author: Mark Edmondson [aut, cre] (<https://orcid.org/0000-0002-8434-3881>), Jennifer Bryan [ctb], Johann deBoer [ctb], Neal Richardson [ctb]
# Maintainer: Mark Edmondson <m@sunholo.com>
# Repository: CRAN
# Date/Publication: 2018-06-21 16:52:39 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
