{% set version = '0.3.0.1' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rlang
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/rlang_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rlang/rlang_{{ version }}.tar.gz
  sha256: 29451db0a3cabd75761d32df47a5d43ccadbde07ecb693ffdd73f122a0b9f348

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: crayon, magrittr, methods, pillar, testthat (>= 2.0.0), covr
requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}sed               # [win]
    - {{posix}}grep              # [win]
    - {{posix}}autoconf
    - {{posix}}automake          # [not win]
    - {{posix}}automake-wrapper  # [win]
    - {{posix}}pkg-config
    - {{posix}}make
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]

  host:
    - r-base

  run:
    - r-base
    - {{native}}gcc-libs         # [win]

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('rlang')"           # [not win]
    - "\"%R%\" -e \"library('rlang')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: http://rlang.tidyverse.org, https://github.com/r-lib/rlang
  license: GPL-3
  summary: A toolbox for working with base types, core R features like the condition system,
    and core 'Tidyverse' features like tidy evaluation.
  license_family: GPL3

# The original CRAN metadata for this package was:

# Package: rlang
# Version: 0.3.0.1
# Title: Functions for Base Types and Core R and 'Tidyverse' Features
# Description: A toolbox for working with base types, core R features like the condition system, and core 'Tidyverse' features like tidy evaluation.
# Authors@R: c( person("Lionel", "Henry", ,"lionel@rstudio.com", c("aut", "cre")), person("Hadley", "Wickham", ,"hadley@rstudio.com", "aut"), person("RStudio", role = "cph") )
# License: GPL-3
# LazyData: true
# ByteCompile: true
# Biarch: true
# Depends: R (>= 3.1.0)
# Suggests: crayon, magrittr, methods, pillar, testthat (>= 2.0.0), covr
# Encoding: UTF-8
# RoxygenNote: 6.1.0.9000
# URL: http://rlang.tidyverse.org, https://github.com/r-lib/rlang
# BugReports: https://github.com/r-lib/rlang/issues
# NeedsCompilation: yes
# Packaged: 2018-10-25 07:46:00 UTC; ripley
# Author: Lionel Henry [aut, cre], Hadley Wickham [aut], RStudio [cph]
# Maintainer: Lionel Henry <lionel@rstudio.com>
# Repository: CRAN
# Date/Publication: 2018-10-25 08:24:20 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
