{% set version = '1.11.8' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-data.table
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/data.table_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/data.table/data.table_{{ version }}.tar.gz
  sha256: dc427465599cadd848b28a78e2fce3362867847b44148252054385999fe566d9

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: bit64, curl, R.utils, knitr, xts, nanotime, zoo
requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]

  host:
    - r-base

  run:
    - r-base
    - {{native}}gcc-libs         # [win]

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('data.table')"           # [not win]
    - "\"%R%\" -e \"library('data.table')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: http://r-datatable.com
  license: MPL-2.0 | file LICENSE
  summary: Fast aggregation of large data (e.g. 100GB in RAM), fast ordered joins, fast add/modify/delete
    of columns by group using no copies at all, list columns, friendly and fast character-separated-value
    read/write. Offers a natural and flexible syntax, for faster development.
  license_family: OTHER

# The original CRAN metadata for this package was:

# Package: data.table
# Version: 1.11.8
# Title: Extension of `data.frame`
# Authors@R: c( person("Matt","Dowle",      role=c("aut","cre"), email="mattjdowle@gmail.com"), person("Arun","Srinivasan", role="aut", email="arunkumar.sriniv@gmail.com"), person("Jan","Gorecki",     role="ctb"), person("Michael","Chirico", role="ctb"), person("Pasha","Stetsenko", role="ctb"), person("Tom","Short",       role="ctb"), person("Steve","Lianoglou", role="ctb"), person("Eduard","Antonyan", role="ctb"), person("Markus","Bonsch",   role="ctb"), person("Hugh","Parsonage",  role="ctb"))
# Depends: R (>= 3.1.0)
# Imports: methods
# Suggests: bit64, curl, R.utils, knitr, xts, nanotime, zoo
# Description: Fast aggregation of large data (e.g. 100GB in RAM), fast ordered joins, fast add/modify/delete of columns by group using no copies at all, list columns, friendly and fast character-separated-value read/write. Offers a natural and flexible syntax, for faster development.
# License: MPL-2.0 | file LICENSE
# URL: http://r-datatable.com
# BugReports: https://github.com/Rdatatable/data.table/issues
# VignetteBuilder: knitr
# ByteCompile: TRUE
# NeedsCompilation: yes
# Packaged: 2018-09-29 08:30:08.301 UTC; mdowle
# Author: Matt Dowle [aut, cre], Arun Srinivasan [aut], Jan Gorecki [ctb], Michael Chirico [ctb], Pasha Stetsenko [ctb], Tom Short [ctb], Steve Lianoglou [ctb], Eduard Antonyan [ctb], Markus Bonsch [ctb], Hugh Parsonage [ctb]
# Maintainer: Matt Dowle <mattjdowle@gmail.com>
# Repository: CRAN
# Date/Publication: 2018-09-30 13:30:03 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
