{% set version = '1.1' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-openssl
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/openssl_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/openssl/openssl_{{ version }}.tar.gz
  sha256: fb5f8d8d856132b8c618cfec3ff19ef7a163c46c9384cb51e65cd131327bbd51

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: testthat, digest, knitr, rmarkdown, jsonlite, jose
requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}sed               # [win]
    - {{posix}}grep              # [win]
    - {{posix}}autoconf
    - {{posix}}automake          # [not win]
    - {{posix}}automake-wrapper  # [win]
    - {{posix}}pkg-config
    - {{posix}}make
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]

  host:
    - r-base

  run:
    - r-base
    - {{native}}gcc-libs         # [win]

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('openssl')"           # [not win]
    - "\"%R%\" -e \"library('openssl')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/jeroen/openssl#readme
  license: MIT + file LICENSE
  summary: Bindings to OpenSSL libssl and libcrypto, plus custom SSH pubkey parsers. Supports
    RSA, DSA and EC curves P-256, P-384 and P-521. Cryptographic signatures can either
    be created and verified manually or via x509 certificates. AES can be used in cbc,
    ctr or gcm mode for symmetric encryption; RSA for asymmetric (public key) encryption
    or EC for Diffie Hellman. High-level envelope functions combine RSA and AES for
    encrypting arbitrary sized data. Other utilities include key generators, hash functions
    (md5, sha1, sha256, etc), base64 encoder, a secure random number generator, and
    'bignum' math methods for manually performing crypto calculations on large multibyte
    integers.
  license_family: MIT

# The original CRAN metadata for this package was:

# Package: openssl
# Type: Package
# Title: Toolkit for Encryption, Signatures and Certificates Based on OpenSSL
# Version: 1.1
# Authors@R: c(person("Jeroen", "Ooms", role = c("aut", "cre"), email = "jeroen@berkeley.edu", comment = c(ORCID = "0000-0002-4035-0289")), person("Oliver", "Keyes", role = "ctb"))
# Description: Bindings to OpenSSL libssl and libcrypto, plus custom SSH pubkey parsers. Supports RSA, DSA and EC curves P-256, P-384 and P-521. Cryptographic signatures can either be created and verified manually or via x509 certificates. AES can be used in cbc, ctr or gcm mode for symmetric encryption; RSA for asymmetric (public key) encryption or EC for Diffie Hellman. High-level envelope functions combine RSA and AES for encrypting arbitrary sized data. Other utilities include key generators, hash functions (md5, sha1, sha256, etc), base64 encoder, a secure random number generator, and 'bignum' math methods for manually performing crypto calculations on large multibyte integers.
# License: MIT + file LICENSE
# URL: https://github.com/jeroen/openssl#readme
# BugReports: https://github.com/jeroen/openssl/issues
# SystemRequirements: OpenSSL >= 1.0.1
# VignetteBuilder: knitr
# Suggests: testthat, digest, knitr, rmarkdown, jsonlite, jose
# RoxygenNote: 6.1.1
# NeedsCompilation: yes
# Packaged: 2018-11-15 13:15:06 UTC; jeroen
# Author: Jeroen Ooms [aut, cre] (<https://orcid.org/0000-0002-4035-0289>), Oliver Keyes [ctb]
# Maintainer: Jeroen Ooms <jeroen@berkeley.edu>
# Repository: CRAN
# Date/Publication: 2018-11-15 14:20:03 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
